filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      json.message_key: log
      templates:
        - condition:
            contains:
              docker.container.labels.org_label-schema_name: Elasticsearch
          config:
            - module: elasticsearch
              server:
                enabled: true
                var.paths:
                  - /var/lib/docker/containers/${data.docker.container.id}/*.log

filebeat.inputs:
- type: httpjson
  config_version: 2
  interval: 1m
  url: http://localhost:5066
  processors:
  - decode_json_fields:
      fields: ["message"]
      target: "json"

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  protocol: '${ELASTICSEARCH_PROTOCOL:http}'
  ssl.enabled: ${ELASTICSEARCH_SSL:false}
  ssl.verification_mode: "${ELASTICSEARCH_VERIFICATION_MODE:none}"
  ssl.certificate_authorities: ["${ELASTICSEARCH_CERTIFICATE_AUTHORITIES:}"]
  ssl.certificate: "${ELASTICSEARCH_CERTIFICATE:}"
  ssl.key: "${ELASTICSEARCH_CERTIFICATE_KEY:}"

http.enabled: true
http.host: 0.0.0.0
http.port: 5066

logging.metrics.enabled: false

monitoring.cluster_uuid: "${CLUSTER_UUID}"
