metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  protocol: '${ELASTICSEARCH_PROTOCOL:http}'
  ssl.enabled: ${ELASTICSEARCH_SSL:false}
  ssl.verification_mode: "${ELASTICSEARCH_VERIFICATION_MODE:none}"
  ssl.certificate_authorities: ["${ELASTICSEARCH_CERTIFICATE_AUTHORITIES:}"]
  ssl.certificate: "${ELASTICSEARCH_CERTIFICATE:}"
  ssl.key: "${ELASTICSEARCH_CERTIFICATE_KEY:}"

http.enabled: true
http.host: localhost
http.port: 5066

logging.metrics.enabled: false
