# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.9/metricbeat-module-elasticsearch.html

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: 
    - "https://es01:9200"
  username: "elastic"
  password: "test"
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
