# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.9/metricbeat-module-kibana.html

- module: kibana
  xpack.enabled: true
  period: 10s
  hosts: 
    - "https://kibana:5601"
  #basepath: ""
  username: "elastic"
  password: "test"
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
